export const paths = {
  login: "/login",
  dashboard: "/dashboard",
  sales: "/sales",
  inventory: "/inventory",
  productDetail: "/inventory/:id",
  customers: "/customers",
  customerDetail: "/customers/:id",
  transactions: "/transactions",
  transactionDetail: "/transactions/:id",
  // taxReport: "/reports/tax",
  quoteReport: "/reports/quotes",
  statistics: "/statistics",
  // barcode: "/barcode",
  employees: "/employees",
  employeeDetail: "/employees/:id",
  purchaseReceipts: "/purchase-receipts",
  settings: "/settings",
  forbidden: "/forbidden",
};